[package]
name = "intermezzos"
version = "0.1.0"
authors = ["The intermezzOS team"]
build = "build.rs"

[dependencies]
vga = { path = "../vga" }
rlibc = "1.0.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
